# Generated by Django 3.1.3 on 2020-11-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0002_auto_20201112_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='anioPublicacion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='manga',
            name='anioPublicacion',
            field=models.CharField(max_length=50),
        ),
    ]
